services:
  db:
    image: postgis/postgis:18-3.6-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: runtogether
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d runtogether"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432
  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
  cache:
    image: redis:8.4-alpine
    restart: always
    ports:
      - '6379:6379'
volumes:
  postgres_data: