# Generated by Django 6.0 on 2026-01-23 21:33

import django.db.models.deletion
import django_editorjs_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("city", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                (
                    "description",
                    django_editorjs_fields.fields.EditorJsJSONField(
                        blank=True, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "city",
                    models.ForeignKey(
                        help_text="City where the user resides",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="clubs",
                        to="city.city",
                    ),
                ),
            ],
        ),
    ]
