# Generated by Django 6.0 on 2026-01-23 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("club", "0001_initial"),
        ("relation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="members",
            field=models.ManyToManyField(
                related_name="clubs",
                through="relation.ClubMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
