# Generated by Django 6.0 on 2026-01-21 20:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="clubmembership",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="clubmembership",
            name="club",
        ),
        migrations.RemoveField(
            model_name="clubmembership",
            name="user",
        ),
        migrations.AlterField(
            model_name="club",
            name="description",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1), ("image", 2)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"form_classname": "title"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                },
                null=True,
            ),
        ),
    ]
