# Generated by Django 6.0 on 2026-01-21 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0002_alter_clubmembership_unique_together_and_more"),
        ("relation", "0002_clubmembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="members",
            field=models.ManyToManyField(
                related_name="clubs",
                through="relation.ClubMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="ClubMembership",
        ),
    ]
