# Generated by Django 6.0 on 2026-01-22 19:21

import django_editorjs_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0003_alter_club_members_delete_clubmembership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="description",
            field=django_editorjs_fields.fields.EditorJsJSONField(),
        ),
    ]
