# Generated by Django 6.0 on 2026-01-23 20:47

import django_editorjs_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0004_alter_club_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="description",
            field=django_editorjs_fields.fields.EditorJsJSONField(
                blank=True, null=True
            ),
        ),
    ]
