# Generated by Django 6.0 on 2026-01-24 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("city", "0002_remove_city_city_clean_name_gin_trgm_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.ForeignKey(
                blank=True,
                help_text="City where the user resides",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="users",
                to="city.city",
            ),
        ),
    ]
