# Generated by Django 6.0 on 2026-01-07 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("city", "0004_city_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.ForeignKey(
                default=2988507,
                help_text="City where the user resides",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="users",
                to="city.city",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="garmin_url",
            field=models.URLField(
                blank=True,
                help_text="URL of the user's Garmin profile",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="strava_url",
            field=models.URLField(
                blank=True,
                help_text="URL of the user's Strava profile",
                max_length=500,
                null=True,
            ),
        ),
    ]
