# Generated by Django 6.0 on 2026-01-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigIntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=60)),
                ("clean_name", models.CharField(max_length=60)),
                ("latitude", models.DecimalField(decimal_places=5, max_digits=7)),
                ("longitude", models.DecimalField(decimal_places=5, max_digits=8)),
                ("country", models.CharField(max_length=2)),
                ("last_modified", models.DateField()),
            ],
        ),
    ]
