# Generated by Django 6.0 on 2026-01-23 21:33

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigIntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=60)),
                ("clean_name", models.CharField(max_length=60)),
                ("latitude", models.DecimalField(decimal_places=5, max_digits=7)),
                ("longitude", models.DecimalField(decimal_places=5, max_digits=8)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
                ),
                ("country", models.CharField(max_length=2)),
                ("population", models.BigIntegerField(default=0)),
                ("last_modified", models.DateField()),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["clean_name"],
                        name="city_clean_name_gin_trgm_idx",
                        opclasses=["gin_trgm_ops"],
                    )
                ],
            },
        ),
    ]
