# Generated by Django 6.0 on 2026-01-24 12:38

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("city", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="city",
            name="city_clean_name_gin_trgm_idx",
        ),
        migrations.AlterField(
            model_name="city",
            name="country",
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name="city",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="city_clean_name_gin_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.RemoveField(
            model_name="city",
            name="clean_name",
        ),
        migrations.RemoveField(
            model_name="city",
            name="last_modified",
        ),
        migrations.RemoveField(
            model_name="city",
            name="population",
        ),
    ]
