# Generated by Django 6.0 on 2026-01-04 15:39

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0001_initial"),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name="city",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["clean_name"],
                name="city_clean_name_gin_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
