# Generated by Django 6.0 on 2026-01-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("city", "0002_city_city_clean_name_gin_trgm_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="population",
            field=models.BigIntegerField(default=0),
        ),
    ]
