# Generated by Django 6.0 on 2026-01-05 19:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("city", "0003_city_population"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
    ]
