# Generated by Django 6.0 on 2026-01-11 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("race", "0004_alter_race_distance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("favorited", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("none", "Aucun lien"),
                            ("interested", "Intéressé"),
                            ("registered", "Inscrit"),
                            ("search_bib", "Cherche un dossard"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_links",
                        to="race.race",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="race_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "race"), name="unique_user_race"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("favorited", True),
                            models.Q(("status", "none"), _negated=True),
                            _connector="OR",
                        ),
                        name="must_have_like_or_status",
                    ),
                ],
            },
        ),
    ]
