# Generated by Django 6.0 on 2026-01-05 20:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("date_course", models.DateField()),
                (
                    "date_validated",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the race date is confirmed",
                    ),
                ),
                (
                    "inscription_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("not_open", "Inscriptions non ouvertes"),
                            ("open", "Inscriptions en cours"),
                            ("closed", "Inscriptions terminées"),
                            ("terminated", "Course terminée"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("date_inscriptions_open", models.DateField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=8, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=7, null=True
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "race_type",
                    models.CharField(
                        blank=True,
                        choices=[("trail", "Trail"), ("road", "Road")],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("private", models.BooleanField(default=False)),
                ("url_race", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "url_inscriptions",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
    ]
