# Generated by Django 6.0 on 2026-01-23 21:33

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("city", "0001_initial"),
        ("club", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the race", max_length=500),
                ),
                ("date_course", models.DateField(help_text="Date of the race")),
                (
                    "date_validated",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the race date is confirmed",
                    ),
                ),
                (
                    "inscription_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("not_open", "Inscriptions non ouvertes"),
                            ("open", "Inscriptions en cours"),
                            ("closed", "Inscriptions terminées"),
                            ("terminated", "Course terminée"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "date_inscriptions_open",
                    models.DateField(
                        blank=True, help_text="Date when inscriptions open", null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=8, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=7, null=True
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "race_type",
                    models.CharField(
                        blank=True,
                        choices=[("trail", "Trail"), ("road", "Road")],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "private",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the race is limited to a specific club",
                    ),
                ),
                (
                    "url_race",
                    models.URLField(
                        blank=True,
                        help_text="URL of the race",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "url_inscriptions",
                    models.URLField(
                        blank=True,
                        help_text="URL of the inscriptions",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "distance",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        blank=True,
                        default=list,
                        help_text="List of distances in kilometers",
                    ),
                ),
                (
                    "nightrun",
                    models.BooleanField(
                        default=False, help_text="Indicates if the race is run by night"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        help_text="City where the race takes place",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="races",
                        to="city.city",
                    ),
                ),
                (
                    "club_owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Club that owns the race",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="races",
                        to="club.club",
                    ),
                ),
            ],
        ),
    ]
