# Generated by Django 6.0 on 2026-01-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("race", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="distance",
            field=models.JSONField(
                blank=True, help_text="List of distances in kilometers", null=True
            ),
        ),
    ]
