# Generated by Django 6.0 on 2026-01-07 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0004_city_location"),
        ("club", "0001_initial"),
        ("race", "0002_race_distance"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="club_owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Club that owns the race",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="races",
                to="club.club",
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="city",
            field=models.ForeignKey(
                default=2988507,
                help_text="City where the race takes place",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="races",
                to="city.city",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="race",
            name="date_course",
            field=models.DateField(help_text="Date of the race"),
        ),
        migrations.AlterField(
            model_name="race",
            name="date_inscriptions_open",
            field=models.DateField(blank=True, help_text="Date when inscriptions open", null=True),
        ),
        migrations.AlterField(
            model_name="race",
            name="name",
            field=models.CharField(help_text="Name of the race", max_length=500),
        ),
        migrations.AlterField(
            model_name="race",
            name="private",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the race is limited to a specific club",
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="url_inscriptions",
            field=models.URLField(
                blank=True,
                help_text="URL of the inscriptions",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="url_race",
            field=models.URLField(blank=True, help_text="URL of the race", max_length=500, null=True),
        ),
    ]
