# Generated by Django 6.0 on 2026-01-07 19:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("race", "0003_race_club_owner_alter_race_city_and_more"),
    ]

    operations = [
        # 1️⃣ Ajouter une colonne temporaire
        migrations.RunSQL("""
            ALTER TABLE race_race
            ADD COLUMN distance_tmp double precision[];
        """),
        # 2️⃣ Convertir jsonb → float[]
        migrations.RunSQL("""
            UPDATE race_race
            SET distance_tmp = (
                SELECT array_agg(x::double precision)
                FROM jsonb_array_elements_text(distance) AS x
            );
        """),
        # 3️⃣ Supprimer l’ancienne colonne jsonb
        migrations.RunSQL("""
            ALTER TABLE race_race
            DROP COLUMN distance;
        """),
        # 4️⃣ Renommer la nouvelle colonne
        migrations.RunSQL("""
            ALTER TABLE race_race
            RENAME COLUMN distance_tmp TO distance;
        """),
        # 5️⃣ Dire à Django que le champ est maintenant un ArrayField
        migrations.AlterField(
            model_name="race",
            name="distance",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                blank=True,
                default=list,
                help_text="List of distances in kilometers",
            ),
        ),
    ]
