# Generated by Django 6.0 on 2026-01-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("race", "0004_alter_race_distance"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="nightrun",
            field=models.BooleanField(default=False, help_text="Indicates if the race is run by night"),
        ),
    ]
